### ISSUE TITLE
Putting a max higher than what is available defaults to 10

### ISSUE THREAD

**Issue by AaronAnz** [mitchhymel/GooglePlayMusicAPI#3]
For example: 100 available songs for my search term "Apathy" on the website. If I put 101 into GooglePlayMusicClient, it defaults to 10 returned.

**Comment by mitchhymel** [comment]
This is due to a weirdness in behavior of Google's API. See https://github.com/simon-weber/gmusicapi/issues/520 for full explanation. Should be fixed with 05c1845e3a8e5def62c7fd42a2679e4e3f034209
